Repository pdepend/pdepend, pull requests merged in 2019-08, with the labels that each got.

#377 Extend test matrix & do only one job per build on Travis
  .travis.yml
Labels: Build scripts, Enhancement, Testing

#384 Add Gitter badge
  README.md
Labels: Documentation, Enhancement

#387 Add the issue templates to PHP Depend
  .gitattributes
  .github/ISSUE_TEMPLATE/1_Bug.md
  .github/ISSUE_TEMPLATE/2_Feature_Proposal.md
  .github/ISSUE_TEMPLATE/3_Question.md
  .github/ISSUE_TEMPLATE/4_Documentation_and_Website_Issue.md
Labels: Documentation, Enhancement

#385 Fixes for Issues detected by PHPStan
  src/main/php/PDepend/DbusUI/ResultPrinter.php
  src/main/php/PDepend/Metrics/Analyzer/CouplingAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/InheritanceAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/NodeLocAnalyzer.php
  src/main/php/PDepend/Report/Dependencies/Xml.php
  src/main/php/PDepend/Report/Summary/Xml.php
  src/main/php/PDepend/Source/AST/ASTArrayElement.php
  src/main/php/PDepend/Source/AST/ASTCompilationUnitNotFoundException.php
  src/main/php/PDepend/Source/AST/ASTFormalParameter.php
  src/main/php/PDepend/Source/AST/ASTMethod.php
  src/main/php/PDepend/Source/ASTVisitor/AbstractASTVisitor.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Util/IdBuilder.php
Labels: Enhancement, Refactoring

#378 Restore pdepend.org
  .gitignore
  .travis.yml
  composer.json
  src/site/config.php
  src/site/resources/layout.php
  src/site/resources/web/images/command-line.png
  src/site/resources/web/images/jdepend.png
  src/site/resources/web/images/pyramid.png
  src/site/rst/documentation/handbook/command-line/index.rst
  src/site/rst/documentation/handbook/command-line/parts/usage.rst
  src/site/rst/documentation/handbook/reports/parts/overview-pyramid.rst
  src/site/rst/documentation/images/.index.xml
  src/site/rst/documentation/images/jdepend.svg
  src/site/rst/documentation/images/pyramid.svg
  src/site/rst/documentation/software-metrics/index.rst
  src/site/rst/download/index.rst
  src/site/rst/news.rst
  src/site/rst/news/pdepend-2.4.0-released.rst
  src/site/rst/news/pdepend-2.4.1-released.rst
  src/site/rst/news/pdepend-2.5.0-released.rst
  src/site/rst/screenshots.rst
  src/site/rst/screenshots/.gallery.xml
  src/site/rst/screenshots/jdepend.png
  src/site/rst/screenshots/pyramid.png
Labels: Build scripts, Website

#388 Ignore files in the git export that aren't needed to use the project
  .gitattributes
Labels: Build scripts, Enhancement

#390 Upgrade PHPUunit
  composer.json
  src/test/php/PDepend/AbstractTest.php
Labels: Compatiblity, Testing

#391 Add link to Tidelift
  .github/FUNDING.yml
  README.md
Labels: Documentation

#389 Restore website build lost in merge
  .travis.yml
Labels: Build scripts, Testing, Website
