Repository pdepend/pdepend, pull requests merged in 2019-07, with the labels that each got.

#376 Build the phar on travis and publish it to github releases
  .travis.yml
  build.properties
  build.xml
Labels: Build scripts

#375 Fix package type
  composer.json
Labels: Compatiblity, Dependencies, Documentation, Enhancement

#373 USE BSD 3-clause license template
  LICENSE
Labels: Documentation

#381 Fixes #301: Unexpected token error with invokable
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion70Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testParenthesisAroundCallableParsesArguments.php
Labels: Bug, Compatiblity, php7.x
