Repository pdepend/pdepend, pull requests merged in 2019-12, with the labels that each got.

#383 Handle PHP 7.1 level
  phpunit.xml.dist
  src/main/php/PDepend/Source/AST/ASTParameter.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion53.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion54.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion55.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerHelperVersion52.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Source/Tokenizer/Tokenizer.php
  src/main/php/PDepend/Util/Workarounds.php
  src/test/php/PDepend/Bugs/EmptyExceptionMessageInPHP52HelperBug149Test.php
  src/test/php/PDepend/Bugs/ReconfigureXdebugMaxNestingLevelBug133Test.php
  src/test/php/PDepend/Bugs/TokenizerKeywordSubstitutionBug76Test.php
  src/test/php/PDepend/Issues/ReflectionCompatibilityIssue067Test.php
  src/test/php/PDepend/ParserTest.php
  src/test/php/PDepend/Report/Jdepend/XmlTest.php
  src/test/php/PDepend/Source/AST/ASTClassFqnPostfixTest.php
  src/test/php/PDepend/Source/AST/ASTForeachStatementTest.php
  src/test/php/PDepend/Source/AST/ASTListExpressionTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserGenericVersion70Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion54Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion55Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion70Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion71Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPTokenizerHelperVersion52Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPTokenizerInternalTest.php
  src/test/resources/files/Parser/testParserHandlesParentKeywordInFunctionParameterDefaultValue.php
  src/test/resources/files/Source/AST/ASTForeachStatement/testForeachStatementWithKeyAndShortList.php
  src/test/resources/files/Source/AST/ASTForeachStatement/testForeachStatementWithShortList.php
  src/test/resources/files/Source/AST/ASTListExpression/testFunctionVoidReturnType.php
  src/test/resources/files/Source/AST/ASTListExpression/testListExpressionWithArrayAndEmptySlot.php
  src/test/resources/files/Source/AST/ASTListExpression/testListExpressionWithKeys.php
  src/test/resources/files/Source/AST/ASTListExpression/testListExpressionWithKeysAndNestedList.php
  src/test/resources/files/Source/AST/ASTListExpression/testListExpressionWithSquaredBrackets.php
  src/test/resources/files/Source/AST/ASTListExpression/testListExpressionWithSquaredBracketsAndEmptySlot.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion54/testDoubleColonClass.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion55/testDoubleColonClass.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testListExpressionWithKeys.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testListExpressionWithKeysAndNestedList.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testListExpressionWithSquaredBrackets.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testParseList.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testParseListWithSquaredBrackets.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testVoidTypeHintReturn.php
Labels: Compatiblity, Support Request, php5.4, php5.5, php5.6, php5.x, php7.0, php7.1, php7.x

#404 add branch-alias to composer.
  composer.json
Labels: Compatiblity, Enhancement

#398 Allow Symfony 5
  composer.json
  src/main/php/PDepend/DependencyInjection/Configuration.php
  src/main/php/PDepend/DependencyInjection/TreeBuilder.php
Labels: Compatiblity

#420 Ensure reserved keywords are allowed as constant names
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion56Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion70Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion56/testReservedKeyword.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testReservedKeyword.php
Labels: Testing, php5.6

#402 Add pdepend-2.6.0 changelog
  CHANGELOG.md
Labels: Documentation

#419 Add pdepend-2.6.0 changelog
  CHANGELOG.md
Labels: Documentation

#418 Start next PHP levels parser inheritance structure
  src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion73.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
Labels: Compatiblity, php7.0, php7.1, php7.2, php7.3, php7.4

#425 Fix #299 Array concatenation in constant declaration
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion56.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion56Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion56/testConstantArrayConcatenation.php
Labels: Bug, php5.6

#435 Check PHP 7.2 support for Abstract method overriding
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion72/testAbstractMethodOverriding.php
Labels: Compatiblity, Testing, php7.2

#433 Remove the not anymore used PHPTokenizerHelperVersion52
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerHelperVersion52.php
Labels: Refactoring

#400 Remove the not anymore used PHPTokenizerHelperVersion52
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerHelperVersion52.php
Labels: Refactoring

#395 Add missing reserved words that are allowed as const name:
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
Labels: Bug, php7.0

#436 Check PHP 7.3 Array Destructuring supports Reference Assignments
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion73.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion73/testDestructuringArrayReference.php
Labels: Compatiblity, Testing, php7.3

#411 Check PHP 7.3 Array Destructuring supports Reference Assignments
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion73.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion73/testDestructuringArrayReference.php
Labels: Compatiblity, php7.3
