Repository pdepend/pdepend, pull requests merged in 2020-01, with the labels that each got.

#422 Fix PHP 7.4 unit tests compatibility
  .travis.yml
  src/test/php/PDepend/AbstractTest.php
  src/test/php/PDepend/MockBuilder.php
  src/test/php/PDepend/Source/AST/ASTClassTest.php
Labels: Bug, Compatiblity, Testing, php7.4

#409 Check and remove PHP 7.0 TODO comment
  .travis.yml
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion70Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testCallableKeywordAsClassName.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testCallableKeywordAsInterfaceName.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testInsteadofKeywordAsClassName.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testInsteadofKeywordAsInterfaceName.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testKeywordsAsConstants.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testKeywordsAsMethodNames.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testTraitKeywordAsClassName.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testTraitKeywordAsInterfaceName.php
Labels: Compatiblity, Testing, php7.0

#413 Check PHP 7.3 Instanceof Operator accepts Literals
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion73.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion73/testInstanceOfLiterals.php
Labels: Compatiblity, php7.3

#421 [Travis-CI] Fix unit tests failure detection
  .travis.yml
  src/test/php/PDepend/AbstractTest.php
  src/test/php/PDepend/Bugs/NamespacedConstsAndFunctionsBug00000247Test.php
  src/test/php/PDepend/Source/AST/ASTArtifactTest.php
  src/test/php/PDepend/Source/AST/ASTCallableTest.php
  src/test/php/PDepend/Source/AST/ASTNodeTest.php
  src/test/php/PDepend/Source/AST/ASTSelfReferenceTest.php
  src/test/php/PDepend/Source/AST/ASTStaticReferenceTest.php
  src/test/php/PDepend/Source/ASTVisitor/DefaultVisitorTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion53Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion54Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion55Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion56Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion70Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion71Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
Labels: Bug, Testing

#412 Check PHP 7.3 Trailing Commas are allowed in Calls
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion73.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion73/testTrailingCommasInCall.php
Labels: Compatiblity, php7.3

#414 Implement PHP 7.4 Typed properties
  src/main/php/PDepend/Source/AST/ASTFieldDeclaration.php
  src/main/php/PDepend/Source/AST/ASTFormalParameter.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTypedProperties.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTypedPropertiesSyntaxError.php
Labels: Compatiblity, php7.4

#362 Issue #361 - Support for php:// stream wrappers in \PDepend\Engine
  src/main/php/PDepend/Engine.php
  src/test/php/PDepend/ApplicationTest.php
  src/test/php/PDepend/EngineTest.php
Labels: Compatiblity, Enhancement

#415 Add unit tests for PHP 7.4 features to implement
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testArrowFunctions.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testNullCoalescingAssignmentOperator.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testNumericLiteralSeparator.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTypeCovarianceAndArgumentTypeContravariance.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testUnpackingInsideArrays.php
Labels: Compatiblity, Testing, php7.4

#426 Implement arrow functions fn() =>
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Source/Tokenizer/Tokens.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion73/testArrowFunctions.php
Labels: Compatiblity, Enhancement, php7.4

#427 Fulfill support of PHP 7.4 features
  src/main/php/PDepend/Engine.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion56.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Source/Tokenizer/Tokens.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
Labels: Compatiblity, Enhancement, php7.4

#449 Add changelog for version 2.7.0
  CHANGELOG.md
Labels: Documentation

#452 Add changelog for version 2.7.0
  CHANGELOG.md
Labels: Documentation

#453 Enhance typed properties
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTypedProperties.php
Labels: Compatiblity, Enhancement, php7.4
