Repository pdepend/pdepend, pull requests merged in 2020-05, with the labels that each got.

#475 Fix #474 typed property visibility
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion56Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion56/testStaticArrayProperty.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testSingleTypedProperty.php
Labels: Bug, php7.4

#476 Fix #473 handle skipped variable in destructuring array
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php
  src/test/php/PDepend/Source/AST/ASTListExpressionTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion70Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion71Test.php
  src/test/resources/files/Source/AST/ASTListExpression/testSymmetricArrayDestructuringEmptySlot.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion70/testSymmetricArrayDestructuringEmptySlot.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion71/testSymmetricArrayDestructuringEmptySlot.php
Labels: Bug, Compatiblity, php7.1

#477 Add missing PHPDoc in PHPParserVersion71 and re-order methods
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php
Labels: Documentation, Refactoring

#484 Clean up PHPDoc and fix some edge cases
  src/main/php/PDepend/Metrics/Analyzer/ClassDependencyAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/CyclomaticComplexityAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/DependencyAnalyzer.php
  src/main/php/PDepend/Report/Dependencies/Xml.php
  src/main/php/PDepend/Source/AST/ASTAnonymousClass.php
  src/main/php/PDepend/Source/AST/ASTClassOrInterfaceReference.php
  src/main/php/PDepend/Source/AST/ASTCompilationUnit.php
  src/main/php/PDepend/Source/AST/ASTFieldDeclaration.php
  src/main/php/PDepend/Source/AST/ASTFormalParameter.php
  src/main/php/PDepend/Source/AST/ASTFunction.php
  src/main/php/PDepend/Source/AST/AbstractASTArtifact.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTNode.php
  src/main/php/PDepend/Source/AST/AbstractASTType.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
  src/main/php/PDepend/Util/Cache/Driver/MemoryCacheDriver.php
  src/main/php/PDepend/Util/ConfigurationInstance.php
  src/main/php/PDepend/Util/Coverage/Factory.php
  src/main/php/PDepend/Util/Type.php
  src/main/php/PDepend/Util/Utf8Util.php
  src/main/php/PDepend/Util/Workarounds.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
Labels: Code Style, Refactoring
