Repository pdepend/pdepend, pull requests merged in 2020-06, with the labels that each got.

#487 Support arrow functions return type hints
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testArrowFunctionsWithReturnType.php
Labels: Compatiblity, php7.4

#478 Fix #472 Use the current token instead of the first inner one to determine the class start
  src/main/php/PDepend/Source/AST/AbstractASTType.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion71Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion71/testClassStartLine.php
Labels: Bug, php7.1

#485 Use the right tool for casting int to string
  src/main/php/PDepend/Report/Summary/Xml.php
Labels: Code Style, Refactoring

#479 Fix #299 Class constant expression declaration
  src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion56.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Source/Tokenizer/FullTokenizer.php
  src/test/php/PDepend/Bugs/ClassConstantAsArrayExpressionBug299Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testConstantArrayConcatenation.php
  src/test/resources/files/bugs/299/testConstantArrayConcatenation.php
Labels: Bug

#481 Update the changelog and build properties for version 2.8.0
  CHANGELOG.md
  build.properties
Labels: Documentation
