Repository pdepend/pdepend, pull requests merged in 2021-05, with the labels that each got.

#535 Allow use of trailing comma in closure use list introduced in PHP 8.0
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion80Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTrailingCommaInClosureUseListError.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion80/testTrailingCommaInClosureUseList.php
Labels: Compatiblity, php8.0, php8.x

#534 Allow use of trailing comma in formal parameters list introduced in PHP 8.0
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion80Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testTrailingCommaInParameterList.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion80/testTrailingCommaInParameterList.php
Labels: php8.0, php8.x

#537 (fix): match expression does not have namespace
  src/main/php/PDepend/Source/AST/AbstractASTNode.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/MatchExpressionTest.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/MatchExpression/testMatchExpressionWithNamespace.php
Labels: Bug

#538 Add named argument value as child to make it discoverable
  src/main/php/PDepend/Source/AST/ASTNamedArgument.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/NamedArgumentsTest.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/NamedArguments/testNamedArgumentsFindDirectVariable.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/NamedArguments/testNamedArgumentsFindVariable.php
Labels: php8.0, php8.x

#540 (feat): throw expression
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/ThrowExpressionTest.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/ThrowExpression/testNullcoalescingThrow.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/ThrowExpression/testShorthandTernaryOperator.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/ThrowExpression/testTernaryOperator.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/ThrowExpression/testThrowFromArrowFunction.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/ThrowExpression/testThrowFromArrowFunctionAsParameter.php
Labels: php8.0, php8.x
