Repository pdepend/pdepend, pull requests merged in 2021-07, with the labels that each got.

#549 Add test with comments
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/ConstructorPropertyPromotionTest.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/ConstructorPropertyPromotion/testConstructorPropertyPromotionWithComments.php
Labels: Testing, php8.0, php8.x

#551 Allow null and false in union type for typed properties
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion80Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion80/testNullableTypedProperties.php
Labels: Bug, php8.0, php8.x

#552 Allow null-safe operator anywhere object operator is allowed
  src/main/php/PDepend/Metrics/Analyzer/HalsteadAnalyzer.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/NullsafeOperatorTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/PHPParserVersion80Test.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/NullsafeOperator/testNullsafeOperatorChain.php
Labels: Bug, php8.0, php8.x

#550 Allow multiple arguments in invocation
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserGenericVersion70Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserGenericVersion70/testMultipleArgumentsInInvocation.php
Labels: Bug

#554 Prepare release 2.10.0
  CHANGELOG.md
  build.properties
Labels: Documentation
