Repository pdepend/pdepend, pull requests merged in 2021-01, with the labels that each got.

#486 Clean up PHPDoc and fix some edge cases
  src/main/php/PDepend/Metrics/Analyzer/DependencyAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/NodeLocAnalyzer.php
  src/main/php/PDepend/Report/Dependencies/Xml.php
  src/main/php/PDepend/Report/Jdepend/Chart.php
  src/main/php/PDepend/Report/Summary/Xml.php
  src/main/php/PDepend/Source/AST/ASTClassReference.php
  src/main/php/PDepend/Source/AST/ASTCompilationUnit.php
  src/main/php/PDepend/Source/AST/ASTNode.php
  src/main/php/PDepend/Source/AST/ASTParameter.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTClassOrInterface.php
  src/main/php/PDepend/Source/AST/AbstractASTNode.php
  src/main/php/PDepend/Source/AST/AbstractASTType.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/main/php/PDepend/Util/Cache/Driver/MemoryCacheDriver.php
Labels: Code Style, Refactoring

#500 Switch to GitHub Actions
  .github/workflows/coverage.yml
  .github/workflows/phar.yml
  .github/workflows/tests.yml
  .github/workflows/website.yml
  .travis.yml
  composer.json
  src/test/php/PDepend/AbstractTest.php
  src/test/php/PDepend/Bugs/EndLessLoopBetweenForParentClassBug152Test.php
  src/test/php/PDepend/EngineTest.php
  src/test/php/PDepend/Issues/NamespaceSupportIssue002Test.php
  src/test/php/PDepend/ParserTest.php
  src/test/php/PDepend/Report/Dependencies/XmlTest.php
  src/test/php/PDepend/Report/Jdepend/ChartTest.php
  src/test/php/PDepend/Util/ImageConvertTest.php
Labels: Testing

#503 Add missing environment variables
  .github/workflows/website.yml
Labels: Documentation

#513 Fix PHPDoc Blocks
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
Labels: Documentation
