Repository pdepend/pdepend, pull requests merged in 2021-04, with the labels that each got.

#520 Allow trailing commas in grouped use declarations in PHP 7.2+
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/AttributeTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/ConstructorPropertyPromotionTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/MatchExpressionTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/NamedArgumentsTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/NullsafeOperatorTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/PHPParserVersion80Test.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/UnionTypesTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion72/testGroupUseStatementTrailingComma.php
Labels: Compatiblity, php7.x

#525 Handle PHP 8.0 null and false type hint
  src/main/php/PDepend/Source/AST/ASTScalarType.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/AttributeTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/MatchExpressionTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/NamedArgumentsTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/NullsafeOperatorTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/UnionTypesTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion80Test.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/UnionTypes/testUnionTypes.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/UnionTypes/testUnionTypesAsReturn.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/UnionTypes/testUnionTypesStandaloneNull.php
Labels: Compatiblity, php8.0, php8.x

#526 Allow catch without variable for PHP >= 8.0
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion80Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testCatchWithoutVariable.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion80/testCatchWithoutVariable.php
Labels: Compatiblity, php8.0, php8.x

#528 Allow nested arrays in attributes
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/NamedArgumentsTest.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/Attribute/testAttribute.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/NamedArguments/testNamedArgumentsInInstances.php
  src/test/resources/files/Source/Language/PHP/Features/PHP80/NamedArguments/testNamedArgumentsWithArrays.php
Labels: Bug, php8.0, php8.x

#529 Prepare the release of version 2.9.1
  CHANGELOG.md
  build.properties
Labels: Documentation
