Repository pdepend/pdepend, pull requests merged in 2022-09, with the labels that each got.

#622 Fix ASTEnum serialization
  src/main/php/PDepend/Source/AST/ASTEnum.php
  src/main/php/PDepend/Source/Builder/Builder.php
  src/main/php/PDepend/Source/Builder/BuilderContext.php
  src/main/php/PDepend/Source/Builder/BuilderContext/GlobalBuilderContext.php
  src/test/php/PDepend/Source/AST/ASTEnumTest.php
Labels: Bug

#627 Add tests for fetching properties of enums in const expressions
  src/main/php/PDepend/Source/AST/ASTNamespace.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP82/FetchPropertiesOfEnumsInConstExpressionsTest.php
  src/test/resources/files/Source/Language/PHP/Features/PHP82/FetchPropertiesOfEnumsInConstExpressions/testEnumConst.php
  src/test/resources/files/Source/Language/PHP/Features/PHP82/FetchPropertiesOfEnumsInConstExpressions/testVariousUsages.php
Labels: php8.x, php8.2

#630 Fix parsing of by-reference vararg parameters
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion81.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion80Test.php
  src/test/resources/files/Source/Language/PHP/PHPParserVersion80/testFunctionParameterTypeHintByReferenceVariableArguments.php
Labels: Bug, php8.x, php8.1

#631 Fix enum visit
  src/main/php/PDepend/Metrics/Analyzer/ClassLevelAnalyzer.php
  src/main/php/PDepend/Source/ASTVisitor/AbstractASTVisitor.php
Labels: php8.1

#633 Fix parsing for new with parentheses
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/test/php/PDepend/Issues/NewClassInstanceTest.php
  src/test/resources/files/issues/601-new-with-expression.php
Labels: Bug
