Repository pdepend/pdepend, pull requests merged in 2024-05, with the labels that each got.

#787 Pds composer script names
  composer.json
Labels: CLI

#806 Use native type for nulled property
  scripts/update-version.php
  src/main/php/PDepend/Engine.php
  src/main/php/PDepend/Input/Iterator.php
  src/main/php/PDepend/Metrics/AbstractCachingAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/ClassDependencyAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/ClassLevelAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/CrapIndexAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/CyclomaticComplexityAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/HalsteadAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/MaintainabilityIndexAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/NPathComplexityAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/NodeLocAnalyzer.php
  src/main/php/PDepend/Source/AST/ASTArtifactList/CollectionArtifactFilter.php
  src/main/php/PDepend/Source/AST/ASTCompilationUnit.php
  src/main/php/PDepend/Source/AST/ASTNamespace.php
  src/main/php/PDepend/Source/AST/ASTParameter.php
  src/main/php/PDepend/Source/AST/ASTParentReference.php
  src/main/php/PDepend/Source/AST/ASTProperty.php
  src/main/php/PDepend/Source/AST/AbstractASTArtifact.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTNode.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
  src/main/php/PDepend/Source/Tokenizer/Token.php
  src/main/php/PDepend/TextUI/Command.php
  src/main/php/PDepend/Util/Cache/CacheFactory.php
  src/main/php/PDepend/Util/Cache/Driver/File/FileCacheDirectory.php
  src/main/php/PDepend/Util/Cache/Driver/MemoryCacheDriver.php
  src/main/php/PDepend/Util/Configuration.php
  src/test/php/PDepend/AbstractTestCase.php
  src/test/php/PDepend/Integration/BuilderParserCacheTest.php
  src/test/php/PDepend/Metrics/Analyzer/ClassDependencyAnalyzerTest.php
  src/test/php/PDepend/Metrics/Analyzer/CodeRankAnalyzerTest.php
  src/test/php/PDepend/Metrics/Analyzer/DependencyAnalyzerTest.php
  src/test/php/PDepend/Report/Dependencies/XmlTest.php
  src/test/php/PDepend/Report/Dummy/Logger.php
  src/test/php/PDepend/Report/Jdepend/ChartTest.php
  src/test/php/PDepend/Report/Jdepend/XmlTest.php
  src/test/php/PDepend/Report/Summary/AnalyzerNodeAndProjectAwareDummy.php
  src/test/php/PDepend/Report/Summary/AnalyzerNodeAwareDummy.php
  src/test/php/PDepend/Report/Summary/AnalyzerProjectAwareDummy.php
  src/test/php/PDepend/Report/Summary/XmlTest.php
  src/test/php/PDepend/Source/AST/ASTParentReferenceTest.php
  src/test/php/PDepend/Util/Cache/Driver/File/FileCacheDirectoryTest.php
  src/test/php/PDepend/Util/Cache/Driver/File/FileCacheGarbageCollectorTest.php
  src/test/php/PDepend/Util/Cache/Driver/FileCacheDriverTest.php
Labels: Refactoring

#795 Protect against devision by zero
  src/main/php/PDepend/Util/Coverage/CloverReport.php
Labels: Bug

#807 Handle some null cases
  src/main/php/PDepend/Metrics/Analyzer/NPathComplexityAnalyzer.php
  src/main/php/PDepend/Report/Overview/Pyramid.php
  src/main/php/PDepend/Source/AST/ASTArtifactList/PackageArtifactFilter.php
  src/main/php/PDepend/Source/AST/ASTCompilationUnit.php
  src/main/php/PDepend/Source/AST/ASTMethod.php
  src/main/php/PDepend/Source/AST/ASTNamespace.php
  src/main/php/PDepend/Source/AST/ASTNode.php
  src/main/php/PDepend/Source/AST/ASTParameter.php
  src/main/php/PDepend/Source/AST/AbstractASTArtifact.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTClassOrInterface.php
  src/main/php/PDepend/Source/AST/AbstractASTNode.php
  src/main/php/PDepend/Source/AST/AbstractASTType.php
  src/main/php/PDepend/Source/ASTVisitor/AbstractASTVisitor.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion81.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion82.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Source/Parser/MissingValueException.php
  src/main/php/PDepend/Source/Parser/TokenStreamEndException.php
  src/main/php/PDepend/TextUI/ResultPrinter.php
  src/main/php/PDepend/Util/Cache/Driver/FileCacheDriver.php
  src/main/php/PDepend/Util/Coverage/CloverReport.php
  src/main/php/PDepend/Util/IdBuilder.php
  src/main/php/PDepend/Util/ImageConvert.php
Labels: Refactoring, PHPStan

#743 Clean up PHP parser
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion81.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion82.php
  src/test/php/PDepend/Bugs/NamespacedConstsAndFunctionsBug00000247Test.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP80/PHPParserVersion80TestCase.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/ArrayUnpackingWithStringKeysTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/EnumTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/ExplicitOctalNotationTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/FinalClassConstantTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/FirstClassCallableSyntaxTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/FirstClassCallableTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/InInitializersTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/IntersectionTypesTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/NeverReturnTypeTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/PHPParserVersion81TestCase.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/ReadonlyClassTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/ReadonlyPropertiesTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP82/TrueTypeTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion80Test.php
Labels: Refactoring, Testing, php8.x

#812 Remove remaning Symfony legacy code
  src/main/php/PDepend/DependencyInjection/TreeBuilderFactory.php
Labels: Refactoring, Dependencies

#817 Minor cleanup
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
Labels: Code Style

#818 Fix coverage for ParserBug713Test
  src/test/php/PDepend/Bugs/ParserBug713Test.php
Labels: Testing, Documentation

#815 Merge latest changes from master
  .github/workflows/coverage.yml
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/test/php/PDepend/Bugs/ParserBug713Test.php
  src/test/resources/files/bugs/713/testConstantArrayIndexIsset.php
Labels: Bug

#820 Also consider fallback case for home dir test
  src/test/php/PDepend/Util/FileUtilTest.php
Labels: Bug, Testing

#822 [3.x[ Suhosin Workaround Removal
  src/bin/pdepend.php
Labels: Compatiblity, php7.x, Refactoring, php8.x

#810 Use unpacking inside arrays
  src/main/php/PDepend/Report/Overview/Pyramid.php
  src/main/php/PDepend/Report/Summary/Xml.php
  src/main/php/PDepend/Source/AST/ASTAnonymousClass.php
  src/main/php/PDepend/Source/AST/ASTClassOrInterfaceReference.php
  src/main/php/PDepend/Source/AST/ASTConstantDeclarator.php
  src/main/php/PDepend/Source/AST/ASTDeclareStatement.php
  src/main/php/PDepend/Source/AST/ASTEnum.php
  src/main/php/PDepend/Source/AST/ASTFormalParameter.php
  src/main/php/PDepend/Source/AST/ASTFunction.php
  src/main/php/PDepend/Source/AST/ASTIncludeExpression.php
  src/main/php/PDepend/Source/AST/ASTMethod.php
  src/main/php/PDepend/Source/AST/ASTParentReference.php
  src/main/php/PDepend/Source/AST/ASTRequireExpression.php
  src/main/php/PDepend/Source/AST/ASTSelfReference.php
  src/main/php/PDepend/Source/AST/ASTSwitchLabel.php
  src/main/php/PDepend/Source/AST/ASTTraitAdaptationAlias.php
  src/main/php/PDepend/Source/AST/ASTVariableDeclarator.php
  src/main/php/PDepend/Source/AST/AbstractASTClassOrInterface.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
Labels: php7.4, Refactoring

#821 Correct nullable return values
  src/main/php/PDepend/Metrics/Analyzer/CodeRankAnalyzer/InheritanceStrategy.php
  src/main/php/PDepend/Report/Dependencies/Xml.php
  src/main/php/PDepend/Report/Summary/Xml.php
  src/main/php/PDepend/Source/AST/ASTEnum.php
  src/main/php/PDepend/Source/AST/ASTFunction.php
  src/main/php/PDepend/Source/AST/ASTTraitUseStatement.php
  src/main/php/PDepend/Source/AST/AbstractASTArtifact.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTClassOrInterface.php
  src/main/php/PDepend/Source/AST/AbstractASTType.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
  src/main/php/PDepend/Source/Parser/SymbolTable.php
Labels: PHPStan

#830 Handle remaning null values
  phpstan.neon
  src/main/php/PDepend/Metrics/Analyzer/CodeRankAnalyzer/MethodStrategy.php
  src/main/php/PDepend/Metrics/Analyzer/CodeRankAnalyzer/PropertyStrategy.php
  src/main/php/PDepend/Metrics/Analyzer/CouplingAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/DependencyAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/NodeCountAnalyzer.php
  src/main/php/PDepend/Source/AST/ASTCompilationUnit.php
  src/main/php/PDepend/Source/AST/ASTParameter.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPParserVersion82.php
  src/test/php/PDepend/Source/AST/ASTParameterTest.php
Labels: PHPStan

#746 Seal up AbstractPHPParser
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
Labels: Refactoring

#831 Address some issues reported by PHPCS
  src/main/php/PDepend/Application.php
  src/main/php/PDepend/DependencyInjection/TreeBuilderFactory.php
  src/main/php/PDepend/Source/AST/ASTArguments.php
  src/main/php/PDepend/Source/AST/ASTFieldDeclaration.php
  src/main/php/PDepend/Source/AST/ASTFormalParameter.php
  src/main/php/PDepend/Source/AST/ASTProperty.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTType.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
Labels: Code Style

#835 Enable Scrutinizer Analysis (3.x)
  .scrutinizer.yml
Labels: Build scripts

#836 Enable Scrutinizer Analysis (2.x)
  .scrutinizer.yml
Labels: Build scripts

#850 Resolve mixed types
  phpstan.neon
  src/main/php/PDepend/DbusUI/ResultPrinter.php
  src/main/php/PDepend/Engine.php
  src/main/php/PDepend/Input/Iterator.php
  src/main/php/PDepend/Metrics/AbstractAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer.php
  src/main/php/PDepend/Metrics/Analyzer/CodeRankAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/CrapIndexAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/DependencyAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/MaintainabilityIndexAnalyzer.php
  src/main/php/PDepend/Metrics/AnalyzerIterator.php
  src/main/php/PDepend/ProcessListener.php
  src/main/php/PDepend/Report/Jdepend/Chart.php
  src/main/php/PDepend/Report/Jdepend/Xml.php
  src/main/php/PDepend/Report/Overview/Pyramid.php
  src/main/php/PDepend/Source/AST/ASTAnonymousClass.php
  src/main/php/PDepend/Source/AST/ASTClassOrInterfaceReference.php
  src/main/php/PDepend/Source/AST/ASTCompilationUnit.php
  src/main/php/PDepend/Source/AST/ASTConstantDeclarator.php
  src/main/php/PDepend/Source/AST/ASTDeclareStatement.php
  src/main/php/PDepend/Source/AST/ASTEnum.php
  src/main/php/PDepend/Source/AST/ASTFunction.php
  src/main/php/PDepend/Source/AST/ASTIncludeExpression.php
  src/main/php/PDepend/Source/AST/ASTMethod.php
  src/main/php/PDepend/Source/AST/ASTParentReference.php
  src/main/php/PDepend/Source/AST/ASTRequireExpression.php
  src/main/php/PDepend/Source/AST/ASTSelfReference.php
  src/main/php/PDepend/Source/AST/ASTSwitchLabel.php
  src/main/php/PDepend/Source/AST/ASTTraitAdaptationAlias.php
  src/main/php/PDepend/Source/AST/ASTVariableDeclarator.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTClassOrInterface.php
  src/main/php/PDepend/Source/AST/AbstractASTNode.php
  src/main/php/PDepend/Source/AST/AbstractASTType.php
  src/main/php/PDepend/Source/Builder/Builder.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Source/Parser/SymbolTable.php
  src/main/php/PDepend/TextUI/Command.php
  src/main/php/PDepend/TextUI/ResultPrinter.php
  src/main/php/PDepend/TextUI/Runner.php
  src/main/php/PDepend/Util/Cache/CacheDriver.php
  src/main/php/PDepend/Util/Cache/CacheFactory.php
  src/main/php/PDepend/Util/Cache/Driver/File/FileCacheGarbageCollector.php
  src/main/php/PDepend/Util/Cache/Driver/FileCacheDriver.php
  src/main/php/PDepend/Util/Cache/Driver/MemoryCacheDriver.php
  src/main/php/PDepend/Util/ImageConvert.php
  src/test/php/PDepend/Report/DummyAnalyzer.php
  src/test/php/PDepend/Report/Summary/AnalyzerNodeAndProjectAwareDummy.php
  src/test/php/PDepend/Report/Summary/AnalyzerNodeAwareDummy.php
  src/test/php/PDepend/Report/Summary/AnalyzerProjectAwareDummy.php
Labels: PHPStan

#827 Clean up bool compares
  src/main/php/PDepend/DbusUI/ResultPrinter.php
  src/main/php/PDepend/Engine.php
  src/main/php/PDepend/Metrics/AbstractAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/CouplingAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/CrapIndexAnalyzer.php
  src/main/php/PDepend/Metrics/Analyzer/NodeLocAnalyzer.php
  src/main/php/PDepend/Report/Dependencies/Xml.php
  src/main/php/PDepend/Report/Summary/Xml.php
  src/main/php/PDepend/Source/AST/ASTParameter.php
  src/main/php/PDepend/Source/AST/ASTProperty.php
  src/main/php/PDepend/Source/AST/ASTValue.php
  src/main/php/PDepend/Source/AST/AbstractASTCallable.php
  src/main/php/PDepend/Source/AST/AbstractASTClassOrInterface.php
  src/main/php/PDepend/Source/ASTVisitor/AbstractASTVisitor.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPBuilder.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/TextUI/Command.php
  src/main/php/PDepend/TextUI/Runner.php
  src/main/php/PDepend/Util/Cache/Driver/FileCacheDriver.php
  src/main/php/PDepend/Util/ImageConvert.php
  src/main/php/PDepend/Util/Type.php
  src/test/php/PDepend/AbstractTestCase.php
  src/test/php/PDepend/Util/ImageConvertTest.php
Labels: Code Style

#832 Clean up edge cases
  src/main/php/PDepend/DependencyInjection/ExtensionManager.php
  src/main/php/PDepend/Metrics/AnalyzerIterator.php
  src/main/php/PDepend/Report/Jdepend/Chart.php
  src/main/php/PDepend/Source/AST/ASTElseIfStatement.php
  src/main/php/PDepend/Source/AST/AbstractASTNode.php
  src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
  src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php
  src/main/php/PDepend/Util/ImageConvert.php
  src/test/php/PDepend/DependencyInjection/ExtensionManagerTest.php
  src/test/php/PDepend/Metrics/AnalyzerIteratorTest.php
Labels: PHPStan

#864 Clean up getNodeMetrics() return value
  src/main/php/PDepend/Metrics/Analyzer/ClassLevelAnalyzer.php
  src/main/php/PDepend/Metrics/AnalyzerNodeAware.php
Labels: Refactoring

#865 Resolve PHPStan issues at level 2 in tests
  src/test/php/PDepend/AbstractTestCase.php
  src/test/php/PDepend/DependencyInjection/ConfigurationTest.php
  src/test/php/PDepend/Integration/BuilderParserCacheTest.php
  src/test/php/PDepend/ParserTest.php
  src/test/php/PDepend/Report/Jdepend/ChartTest.php
  src/test/php/PDepend/Source/AST/ASTClassFqnPostfixTest.php
  src/test/php/PDepend/Source/AST/ASTClassOrInterfaceReferenceTest.php
  src/test/php/PDepend/Source/AST/ASTClassReferenceTest.php
  src/test/php/PDepend/Source/AST/ASTClassTest.php
  src/test/php/PDepend/Source/AST/ASTConstantDefinitionTest.php
  src/test/php/PDepend/Source/AST/ASTFieldDeclarationTest.php
  src/test/php/PDepend/Source/AST/ASTFunctionPostfixTest.php
  src/test/php/PDepend/Source/AST/ASTFunctionTest.php
  src/test/php/PDepend/Source/AST/ASTInstanceOfExpressionTest.php
  src/test/php/PDepend/Source/AST/ASTListExpressionTest.php
  src/test/php/PDepend/Source/AST/ASTLiteralTest.php
  src/test/php/PDepend/Source/AST/ASTMethodPostfixTest.php
  src/test/php/PDepend/Source/AST/ASTMethodTest.php
  src/test/php/PDepend/Source/AST/ASTNodeTestCase.php
  src/test/php/PDepend/Source/AST/ASTParentReferenceTest.php
  src/test/php/PDepend/Source/AST/ASTPropertyPostfixTest.php
  src/test/php/PDepend/Source/AST/ASTSelfReferenceTest.php
  src/test/php/PDepend/Source/AST/ASTStaticReferenceTest.php
  src/test/php/PDepend/Source/AST/ASTStaticVariableDeclarationTest.php
  src/test/php/PDepend/Source/AST/ASTStringTest.php
  src/test/php/PDepend/Source/AST/ASTTraitReferenceTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/FinalClassConstantTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/InInitializersTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/NullsafeOperatorTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP81/ReadonlyPropertiesTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP82/AllowNullAndFalseAsStandAloneTypesTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP82/TrueTypeTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP83/DynamicClassConstantFetchTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP83/TypedClassConstantsTest.php
  src/test/php/PDepend/Source/Language/PHP/Features/PHP83/UnionTypedClassConstantsTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPBuilderTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserGenericTest.php
  src/test/php/PDepend/Source/Language/PHP/PHPParserVersion81Test.php
Labels: Refactoring, PHPStan
